name: Update Major Version Tag After Release

permissions:
  contents: write # Required for updating tags

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: false
        default: "default-tag"
      major_version:
        type: choice
        description: The major version to update
        options:
          - v5
          - v4
          - v3
          - v2
          - v1
  release:
    types:
      - published

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set Dynamic Environment Variables
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          # Use inputs from workflow_dispatch if provided
          TARGET="${{ github.event.inputs.target }}"
          MAJOR_VERSION="${{ github.event.inputs.major_version }}"
        elif [ "${{ github.event_name }}" == "release" ]; then
          # Use release tag for target, and extract major version (assuming semantic versioning)
          TARGET="${{ github.event.release.tag_name }}"
          MAJOR_VERSION="$(echo $TARGET | cut -d '.' -f1)"
        fi
        echo "TARGET=$TARGET" >> $GITHUB_ENV
        echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
    - name: Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Tag new target
      run: git tag -f ${{ env.MAJOR_VERSION }} ${{ env.TARGET }}
    - name: Push new tag
      run: git push origin ${{ env.MAJOR_VERSION }} --force
